name: CI-CD to EKS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1
  EKS_CLUSTER_NAME: EKS-cluster1   # 👈 change to your cluster name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Verify cluster access
        run: kubectl get nodes

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/namespace.yaml || true
          kubectl apply -f k8s/frontend.yaml
          kubectl apply -f k8s/backend.yaml