name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configure AWS credentials (from GitHub secrets)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1   # change if your cluster is in a different region
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Update kubeconfig for your EKS cluster
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ap-south-1 --name EKS-cluster1

      # Test kubectl connectivity
      - name: Test connection
        run: kubectl get nodes
